/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safedec.views;

import java.util.Arrays;
import javax.swing.JOptionPane;
import safedec.controls.ViewController;
import safedec.models.Customer;
import safedec.service.UserAdminService;
import safedec.service.UserAdminServiceImpl;
/**
 *
 * @author akshayharyani
 */
public class ProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
        updateComponents();
        
    }
    private void updateComponents()
    {
        
        customerIdTextField.setText(ViewController.getInstance().getLoggedInUser().getCustomerId() + "" );
        customerNameTextField.setText(ViewController.getInstance().getLoggedInUser().getCustomerName());

        propertyAddressTextField.setText(ViewController.getInstance().getLoggedInUser().getPropertyAddress());

        phoneNoTextField.setText(ViewController.getInstance().getLoggedInUser().getPhoneNumber());

        emailAddressTextField.setText(ViewController.getInstance().getLoggedInUser().getEmailAddress());

        primaryContactNumberTextField.setText(ViewController.getInstance().getLoggedInUser().getPrimaryContactNumber());

        secondaryContactNumberTextField.setText(ViewController.getInstance().getLoggedInUser().getSecondaryContactNumber());

        licenseCodeTextField.setText(ViewController.getInstance().getLoggedInUser().getLicenseCode());

        masterPassword1.setText(ViewController.getInstance().getLoggedInUser().getMasterPassword());

        // TODO responseCodeField.setText(ViewController.getInstance().getLoggedInUser().getResponseCode());

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        customerIdTextField = new javax.swing.JTextField();
        customerNameTextField = new javax.swing.JTextField();
        propertyAddressTextField = new javax.swing.JTextField();
        phoneNoTextField = new javax.swing.JTextField();
        emailAddressTextField = new javax.swing.JTextField();
        primaryContactNumberTextField = new javax.swing.JTextField();
        secondaryContactNumberTextField = new javax.swing.JTextField();
        licenseCodeTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        masterPassword1 = new javax.swing.JPasswordField();
        masterPassword2 = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("Customer Id");

        jLabel2.setText("Customer Name");

        jLabel3.setText("Property Address");

        jLabel4.setText("Phone No");

        jLabel5.setText("Email Address");

        jLabel6.setText("Primary Contact Number");

        jLabel7.setText("Secondary Contact Number");

        jLabel8.setText("License Code");

        jLabel9.setText("Master Password");

        customerIdTextField.setEditable(false);

        emailAddressTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        saveButton.setText("Save");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        masterPassword1.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(propertyAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(primaryContactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(secondaryContactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(masterPassword2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(licenseCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(masterPassword1))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(customerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(propertyAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(phoneNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(primaryContactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(secondaryContactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(licenseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(masterPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
     // TODO add your handling code here:
        if (!Arrays.equals(masterPassword1.getPassword(), masterPassword2.getPassword())) {
            JOptionPane.showMessageDialog(null, "Your two passwords are inconsistent.\n"
                    + "Please check your input.");
            return;
        }
        
        UserAdminService userAdmin = new UserAdminServiceImpl();
        int customerId = Integer.valueOf(customerIdTextField.getText());
        String customerName = customerNameTextField.getText();
        String propertyAddress = propertyAddressTextField.getText();
        String phoneNumber = phoneNoTextField.getText();
        String emailAddress = emailAddressTextField.getText();
        String primaryContactNumber = primaryContactNumberTextField.getText();
        String secondaryContactNumber = secondaryContactNumberTextField.getText();
        String licenseCode = licenseCodeTextField.getText();
        String masterPassword = String.valueOf(masterPassword1.getPassword());
       // String responseCode = re.getText();
        
        Customer existingCustomerInfo= ViewController.getInstance().getLoggedInUser();
        existingCustomerInfo.setCustomerId(customerId);
        existingCustomerInfo.setCustomerName(customerName);
        existingCustomerInfo.setPropertyAddress(propertyAddress);
        existingCustomerInfo.setPhoneNumber(phoneNumber);
        existingCustomerInfo.setEmailAddress(emailAddress);
        existingCustomerInfo.setPrimaryContactNumber(primaryContactNumber);
        existingCustomerInfo.setSecondaryContactNumber(secondaryContactNumber);
        existingCustomerInfo.setLicenseCode(licenseCode);
        existingCustomerInfo.setMasterPassword(masterPassword);
       // customerInfo.setResponseCode(responseCode);
        
        if (userAdmin.editUser(existingCustomerInfo)) {
            JOptionPane.showMessageDialog(null, "Successfully edit your account.\n"
                    + "You can use your your email: " + emailAddress + "\n"
                    + "as username along with your password to log in later.\n"
                    + "Thank you!");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to edit your account.\n"
                    + "Please check your input.\n"
                    + "Please do not use too long or illegal characters.");
        }
    }//GEN-LAST:event_saveButtonMouseClicked

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customerIdTextField;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JTextField emailAddressTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField licenseCodeTextField;
    private javax.swing.JPasswordField masterPassword1;
    private javax.swing.JPasswordField masterPassword2;
    private javax.swing.JTextField phoneNoTextField;
    private javax.swing.JTextField primaryContactNumberTextField;
    private javax.swing.JTextField propertyAddressTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField secondaryContactNumberTextField;
    // End of variables declaration//GEN-END:variables
}
