/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.designPatterns.safedec.Views;

/**
 *
 * @author akshayharyani
 */
public class ProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ServiceIdLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        ServiceIdField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        ServiceIdField1 = new javax.swing.JTextField();
        ServiceIdField2 = new javax.swing.JTextField();
        ServiceIdField3 = new javax.swing.JTextField();
        ServiceIdField4 = new javax.swing.JTextField();
        ServiceIdField5 = new javax.swing.JTextField();
        ServiceIdField6 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(500, 500));

        ServiceIdLabel.setText("Service Id");
        ServiceIdLabel.setToolTipText("");

        FirstNameLabel.setText("First Name");
        FirstNameLabel.setToolTipText("");

        ServiceIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceIdFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Last Name");

        jLabel2.setText("Email");

        jLabel3.setText("Phone");

        jLabel5.setText("Emergency Contact 1");

        jLabel6.setText("Emergency Contact 2");

        saveButton.setText("save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        ServiceIdField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceIdField1ActionPerformed(evt);
            }
        });

        ServiceIdField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceIdField2ActionPerformed(evt);
            }
        });

        ServiceIdField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceIdField3ActionPerformed(evt);
            }
        });

        ServiceIdField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceIdField4ActionPerformed(evt);
            }
        });

        ServiceIdField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceIdField5ActionPerformed(evt);
            }
        });

        ServiceIdField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceIdField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(FirstNameLabel)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(ServiceIdLabel)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ServiceIdField5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(ServiceIdField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ServiceIdField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ServiceIdField2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ServiceIdField3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ServiceIdField4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ServiceIdField6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServiceIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ServiceIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(ServiceIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ServiceIdField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ServiceIdField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ServiceIdField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ServiceIdField5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ServiceIdField6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(saveButton)
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ServiceIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceIdFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void ServiceIdField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceIdField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceIdField1ActionPerformed

    private void ServiceIdField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceIdField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceIdField2ActionPerformed

    private void ServiceIdField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceIdField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceIdField3ActionPerformed

    private void ServiceIdField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceIdField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceIdField4ActionPerformed

    private void ServiceIdField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceIdField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceIdField5ActionPerformed

    private void ServiceIdField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceIdField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceIdField6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField ServiceIdField;
    private javax.swing.JTextField ServiceIdField1;
    private javax.swing.JTextField ServiceIdField2;
    private javax.swing.JTextField ServiceIdField3;
    private javax.swing.JTextField ServiceIdField4;
    private javax.swing.JTextField ServiceIdField5;
    private javax.swing.JTextField ServiceIdField6;
    private javax.swing.JLabel ServiceIdLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
