package safedec.views;

import java.util.List;
import safedec.models.Alarm;
import safedec.models.MotionSensor;
import safedec.service.DashBoardService;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author akshayharyani
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    
    public DashboardPanel() {
        initComponents();
        updateComponents();
        javax.swing.table.DefaultTableModel sensorModel = (javax.swing.table.DefaultTableModel) SensorsTable.getModel();
     
      

    }

    private void updateComponents()
    {
        DashBoardService dashBoardService = new DashBoardService();
        List<MotionSensor> allSensors = dashBoardService.getAllSensors();
        List< Alarm > allAlarms = dashBoardService.getAllAlarmSensors();
        javax.swing.table.DefaultTableModel sensorModel = (javax.swing.table.DefaultTableModel) SensorsTable.getModel();
        
        for( MotionSensor sensor : allSensors )
        {
            Object[]  tableRow = new Object[8];
            tableRow[0]= sensor.getId();
            tableRow[1]= sensor.getSectionId();
            tableRow[2]= sensor.getIpAddress();
            tableRow[3]= sensor.getPortNumber();
            tableRow[4]= sensor.getLoc().getX1()+","+sensor.getLoc().getY1();
            tableRow[5]= sensor.getPrice();
            tableRow[6] = sensor.isIsCamera();
            
             sensorModel.addRow(tableRow);
        }
        
                javax.swing.table.DefaultTableModel alarmModel = (javax.swing.table.DefaultTableModel) AlarmTable.getModel();
         for( Alarm alarm : allAlarms )
         {
            Object[]  tableRow = new Object[8];
            tableRow[0]= alarm.getId();
            tableRow[1]= alarm.getSectionId();
            tableRow[2]= alarm.getIpAddress();
            tableRow[3]= alarm.getPortNumber();
            tableRow[4]= alarm.getLoc().getX1()+","+alarm.getLoc().getY1();
            tableRow[5]= alarm.getPrice();
            
             alarmModel.addRow(tableRow);
             
         }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        statusCodeLabel = new javax.swing.JLabel();
        statusToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SensorsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AlarmTable = new javax.swing.JTable();

        statusLabel.setText("Status");

        statusCodeLabel.setText("Active");

        statusToggleButton2.setText("Deactivate");
        statusToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusToggleButton2ActionPerformed(evt);
            }
        });

        SensorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{

            },
            new String [] {
                "Sensor Id", "Section Id", "Ip Address", "Port Number", "Pos1", "Pos2", "Price","isCamera"
            }
        ));
        SensorsTable.setToolTipText("");
        jScrollPane1.setViewportView(SensorsTable);

        jLabel1.setText("Sensors");

        jLabel4.setText("Alarms");

        AlarmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{

            },
            new String [] {
                "Alarm Id", "Section Id", "Ip Address", "Port Number", "Pos1", "Price"
            }
        ));
        jScrollPane2.setViewportView(AlarmTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(statusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusCodeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                                .addComponent(statusToggleButton2)))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(statusCodeLabel)
                    .addComponent(statusToggleButton2))
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void statusToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusToggleButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AlarmTable;
    private javax.swing.JTable SensorsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel statusCodeLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JToggleButton statusToggleButton2;
    // End of variables declaration//GEN-END:variables
}
